# Generated by Django 6.0.4 on 2026-04-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_prestamo_notificacioncorreo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=400)),
                ('autor', models.CharField(max_length=200)),
                ('tutor', models.CharField(blank=True, max_length=200)),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('tipo', models.CharField(choices=[('licenciatura', 'Licenciatura'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado')], default='licenciatura', max_length=20)),
                ('area', models.CharField(max_length=200, verbose_name='Área temática')),
                ('resumen', models.TextField(blank=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='tesis/', verbose_name='Archivo PDF')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible para consulta')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tesis',
                'verbose_name_plural': 'Tesis',
                'ordering': ['-anio', 'titulo'],
            },
        ),
    ]
