# Generated by Django 6.0.4 on 2026-04-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_tesis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('titular', 'Titular'), ('auxiliar', 'Auxiliar'), ('asistente', 'Asistente'), ('instructor', 'Instructor')], default='titular', max_length=20)),
                ('ambito', models.CharField(choices=[('nacional', 'Nacional'), ('internacional', 'Internacional')], default='nacional', max_length=20)),
                ('pais', models.CharField(blank=True, max_length=100, verbose_name='País (si es internacional)')),
                ('especialidad', models.CharField(max_length=200)),
                ('biografia', models.TextField(blank=True, verbose_name='Biografía')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profesores/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
    ]
