# Generated by Django 6.0.4 on 2026-04-14 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_profesor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('novedad', 'Novedad literaria'), ('tutorial', 'Tutorial'), ('manual', 'Manual'), ('video', 'Video')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='recursos/', verbose_name='Archivo (PDF, DOC...)')),
                ('url_video', models.URLField(blank=True, verbose_name='URL del video (YouTube, etc.)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='recursos/imagenes/')),
                ('publicado', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False, verbose_name='Destacar en inicio')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos', to=settings.AUTH_USER_MODEL, verbose_name='Publicado por')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
