# Generated by Django 6.0.4 on 2026-04-18 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_solicitudprestamo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RenovacionPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('dias_solicitados', models.PositiveIntegerField(default=7, verbose_name='Días de extensión')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo de la renovación')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('respuesta', models.TextField(blank=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('nueva_fecha', models.DateField(blank=True, null=True, verbose_name='Nueva fecha de devolución')),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovaciones_atendidas', to=settings.AUTH_USER_MODEL)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovaciones', to='biblioteca.prestamo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Renovación de préstamo',
                'verbose_name_plural': 'Renovaciones de préstamo',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
