# Generated by Django 6.0.4 on 2026-04-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0008_renovacionprestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='motivo_solicitud',
            field=models.TextField(blank=True, verbose_name='Motivo de la solicitud de rol'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='rol_aprobado',
            field=models.BooleanField(default=False, verbose_name='Rol aprobado por bibliotecario'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='rol_solicitado',
            field=models.CharField(blank=True, choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor'), ('bibliotecario', 'Bibliotecario'), ('visitante', 'Visitante')], max_length=20, null=True, verbose_name='Rol solicitado'),
        ),
    ]
