# Generated by Django 6.0.4 on 2026-04-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_perfilusuario_motivo_solicitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='motivo_solicitud',
            field=models.TextField(blank=True, verbose_name='Motivo de la solicitud'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol_aprobado',
            field=models.BooleanField(default=False, verbose_name='Rol aprobado'),
        ),
    ]
