# Generated by Django 6.0.4 on 2026-04-24 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_alter_perfilusuario_motivo_solicitud_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tesis',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tesis_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
    ]
