# Generated by Django 6.0.4 on 2026-04-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0011_tesis_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesis',
            name='vistas',
            field=models.PositiveIntegerField(default=0, verbose_name='Visualizaciones'),
        ),
    ]
