from .libros import *
from .prestamos import *
from .tesis import *
from .profesores import *
from .recursos import *
from .usuarios import *
from .solicitudes import *
from .renovaciones import *
from .panel import *
from .categorias import *
from .notificaciones import *
from .general import *